### ISSUE TITLE
How to run on Angular?

### ISSUE THREAD

**Issue by oguzeroglu** [philippfromme/philippfromme#1]
Hey,

I'm having a problem running this on Angular. Maybe this needs more Typescript types or something? Or maybe JQuery?

Best,

Oz

**Comment by pinussilvestrus** [comment]
I would rebuild it from scratch. Markdown, in which this project is 100% written, is not the latest shit anymore. I'd recommend https://asciidoc.org/.

**Comment by oguzeroglu** [comment]
Thanks @pinussilvestrus, that seems like the only way to go. I'm closing the issue.

**Comment by philippfromme** [comment]
You have to use the React.!!
